.TH CRYPTO 1 2024-08-31 Linux

.SH NAME
crypto - cryptography utillity

.SH SYNOPSIS
.B crypto
[\fIOPTION\fR]... [\fIINPUT\fR] [\fIOUTPUT\fR]

.SH DESCRIPTION
crypto is a program designed to let the user encrypt and decrypt data using different cryptographic algorithms.

.SH OPTIONS
.TP
.BR \-e " (default)"
encrypt

.TP
.BR \-d
decrypt

.TP
.BR \-p " <password>"
Input a password as a string with this flag, to either encrypt or decrypt a message.

.TP
.BR \-f " <passfile>"
Input a file containing the password to either encrypt or decrypt a message.

.TP
.BR \-c " <cipher>"
Choose which cipher to encrypt or decrypt. See all supported ciphers under the \fBCIPHERS\fR header.

.SH CIPHERS
.TP
.BR aes128

.TP
.BR aes192

.TP
.BR aes256

.TP
.BR rsa

.SH AUTHOR
Written by Hampus Fridholm.

.SH SEE ALSO
\fBhashing\fR(1)
